version: '2'
services:
  mysql:
    image: mariadb:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: PROJECTNAME
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: docker
  phpfpm:
    depends_on:
      - mysql
    volumes:
      - "./:/var/www/html"
      - "./config/docker/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/docker/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "../../.composer:/var/www/.composer"
    restart: always
    build: ./dockerfiles/php-fpm
    env_file: .env    
    extra_hosts:
      - "PROJECTNAME.dev:192.168.0.1"
    links:
      - mysql:mysql      
  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - "./:/var/www/html"
      - "./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    restart: always
